---
title: "About"
output:
  html_document:
    toc: FALSE
---

This research project is part of the requirements of the Masters of Science (Mathematics and Statistics) at The University of Melbourne. This repo will (attempt to) keep track of all my readings, notes, codes and findings I make as part of my research project (in a nice, readable, webpage). This project will span across three semesters (July 2018 - October 2019), and at some stage there will be a thesis and a presentation.

You can find me at `bklaw@student.unimelb.edu.au`

Other information:

- The project will be about _Multiscale models with Hidden Markov Tree dependency structures, applied mainly to genomic data, to better identify signals, and improve inference on association._
- The official thesis title is _blah_
- My supervisor is [Heejung Shim](https://heejungshim.org)
- I guess that means this project is within the realms of the [Melbourne Integrative Genomics (MIG) group](https://research.unimelb.edu.au/integrative-genomics/MIG-home)

