---
title: "Home"
output:
  html_document:
    toc: TRUE
---

This is a website designed to organise readings, notes and code related to my masters project.

***

## Notes
_Summaries and notes from important readings_

### Multiscale models
- [Wavelet-based Genetic Association Analysis... - Shim and Stephens (2015)](wavelets_shim_stephens_2014.html)

### Background/Genetics
- [A very light genetics glossary](genetics_glossary.html)
- [Intro to RNA-Seq](StatQuest_Intro_RNA_seq.html)
- [Intro to ChIP-Seq](StatQuest_Intro_ChIP_seq.html)

### Mathematical/other

***

## Analysis, derivations, code
_Code chunks, RMarkdowns, LaTeX documents._

### Expectation-Maximisation (EM) derivations

#### Gaussian Mixture Models (GMMs)

- Derivation of EM algorithm applied in a simple (canonical) case of Gaussian Mixture Models (GMM). Written more for my understanding/learning of the steps involved. [PDF file](EM_algo_GMM.pdf)

#### Hidden Markov Trees (HMT)
 
- Derivation of EM algorithm applied to Hidden Markov Trees (HMTs) with the properties as described in Crouse et al (1998). Includes derivation of the steps in the upward/downward or forward/backward algorithm involved in its derivation. [PDF file](EM_algo_HMT.pdf)
 
#### Shim and Stephens (2015)
- Derivation of the EM algorithm to find the latent state probability parameters in the Shim and Stephens (2015) paper. Also extended to incorporate HMT dependencies (rather than independence) between the states at different scales and locations. [PDF file](EM_algo_Shim_Stephens_2015_v2.pdf)

- Augmented E-step of the above EM algorithm, when incorporating the HMT dependencies. This is required so that the intermediate steps of the algorithm uses Bayes Factors and remains in a closed form. [PDF file](EM_algo_Shim_Stephens_E_step.pdf)

#### S & S(2015) extended to Poisson multiscale model case

### Implementation - WaveQTL
Some writings about the simulations and data analysis exercises we undertook around the HMT implementation of the WaveQTL package. This is after all the C++ code for WaveQTL was updated to incorporate the HMT case. See 'code/WaveQTL' and specifically, 'model.cpp' for the new base code incorporating the HMT case.

#### Ad hoc - wavelets
- Brief explorations of data with Haar wavelets [here](Wavelets_in_R.html)
- Brief explorations of the genetic data (from WaveQTL) with Haar wavelets [here](Intro_genotype_wlets.html)
- Brief plots of the WaveQTL outputs [here](Intro_genotype_wlets_plots.html)

#### Simulation - three parameter t-distribution
- Goal here is to figure out how to draw samples from the three parameter (generalised) student's t-distribution.
- Turns out, it's not too bad. See [here](tdist_3_param.html)

#### Simulation - estimating coefficients in data space
- Goal here is to draw samples from the posterior distribution of $\beta_{sl}$, and use the inverse wavelet matrix to convert estimate model coefficients in the data space.
- Due to the HMT priors, it's no longer guaranteed that the posterior variance of $\beta$ at each scale-location is independent (or additive) as per the non-HMT case. Hence, we proceed to estimate the mean and variance quantities through simulation.
- You can see the first iteration of that work [here](sim1_waveqtl_hmt_gamma_phi.html). This was run under the following conditions:
	- Using WaveQTL data (WaveQTL use/do not use vector, non-quantile transformed data)
	- Coefficients from the same levels of the tree were tied together to estimate parameters


#### Simulation - HMT code verification
- Goal here is to simulate wavelet data, using pre-determined parameters (pi, the probability at the head of the tree, and epsilon, the transition probabilities), pass it through the HMT code, and recover the original parameters, therefore verifying the correctness of the HMT code.
- __Work is coming soon__.

***

## Papers, presentations, resources
_Most of the readings and resources I've used._

### Multiscale models
- [Shim and Stephens (2015) - Wavelets for Genomic data](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5795621/)
- [Crouse et al (1998) - Wavelets, HMT](https://ieeexplore.ieee.org/abstract/document/668544)
- [Kolaczyk (1999) - Bayesian Multiscale Models for Poisson](https://www.tandfonline.com/doi/abs/10.1080/01621459.1999.10474197)
- [Xing (2016) - Extends Shim/Stephens (2015) to Poisson](https://search.proquest.com/openview/2b17b34545bbb5c3eab53b48983d41c8/1?pq-origsite=gscholar&cbl=18750&diss=y)
- [Servin and Stephens (2007) - original closed form Bayesian association model](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.0030114)

### Wavelets
- [Morris and Carroll (2006) - data to wavelet space](https://rss.onlinelibrary.wiley.com/doi/abs/10.1111/j.1467-9868.2006.00539.x)
- [Torrence et al - Practical guide to wavelets](https://journals.ametsoc.org/doi/abs/10.1175/1520-0477(1998)079%3C0061:APGTWA%3E2.0.CO;2)

### EM Algorithm, applied to Hidden Markov Models
- [Rabiner (1989) - EM in HMM for speech recognition](https://ieeexplore.ieee.org/abstract/document/18626)
- Bishop's book: Pattern Recognition and Machine Learning
- [Grosse and Srivastava - EM for GMM notes](http://www.cs.toronto.edu/~rgrosse/csc321/mixture_models.pdf)
- [Li - EM for HMM notes](http://www.personal.psu.edu/jol2/course/stat597e/notes2/hmm.pdf)
- [Borman - short tutorial on EM](https://www.cs.utah.edu/~piyush/teaching/EM_algorithm.pdf)

### GLMs
- [Rodriguez - Poisson GLM for count data](https://data.princeton.edu/wws509/notes/c4.pdf)

### Bayesian regression
- [Reich - Bayesian regression](https://www4.stat.ncsu.edu/~reich/ABA/notes/BLR.pdf)
- [Statlect - Bayesian regression](https://www.statlect.com/fundamentals-of-statistics/Bayesian-regression)
